main/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.СategoryListView.as_view(), name='index'),
    path('company', views.company, name='company'),
    path('project', views.project, name='project'),
    path('inform', views.inform, name='inform'),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('shop/', include('shop.urls')),
]

shop/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from shop import views

urlpatterns = [
 
    path('', views.ProductsListView.as_view(), name='shop'),
    # path('<str:value>/', views.ProductsListView.as_view(), name='shop/<str:value>'),
    path('category/<int:category_id>/', views.category_filter, name='category_filter'),
    path('cart_view/',  views.cart_view, name='cart_view'),
    path('detail/<int:pk>/',  
         views.ProductsDetailView.as_view(), 
         name='shop_detail'),
    path('add-item-to-cart/<int:pk>', views.add_item_to_cart, name='add_item_to_cart'),
    path('delete_item/<int:pk>', views.CartDeleteItem.as_view(), name='cart_delete_item'),

]

shop/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
from decimal import Decimal
from django.db.models import Sum

from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import transaction

class Сategory(models.Model):
    name = models.CharField(max_length=255, verbose_name='Назва категорії', default="Без категорії")
    image_url = models.URLField(blank=True, null=True) 
    
    

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='product_name')
    code = models.CharField(max_length=255, verbose_name='product_code')
    price = models.DecimalField(max_digits=20, decimal_places=2)
    unit = models.CharField(max_length=255, blank=True, null=True)
    image_url = models.URLField(blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    сategory = models.ForeignKey(Сategory, on_delete=models.CASCADE, null=True, default="Без категорії" )
    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.name}'

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)
    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.user} --- {self.amount} --- {self.time}'
    
    @staticmethod
    def get_balance(user: User):
        amount = Payment.objects.filter(user=user,
                                      ).aggregate(Sum('amount'))['amount__sum']
        return  amount or Decimal(0)
 


class Order(models.Model):

    STATUS_CART = '1_cart'
    STATUS_WAITING_FOR_PAYMENT = '2_waiting_for_payment'
    STATUS_PAID = '3_paid'
    STATUS_CHOICES= [
        (STATUS_CART, 'cart'),
        (STATUS_WAITING_FOR_PAYMENT, 'waiting_for_payment'),
        (STATUS_PAID, 'paid')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # items = models.ManyToManyField(OrderItem, related_name='orders')
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=STATUS_CART)
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    payment = models.ForeignKey(Payment, on_delete=models.PROTECT, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.user} --- {self.amount}'
    
    @staticmethod
    def get_cart(user: User):
        cart = Order.objects.filter(user=user,
                                    status=Order.STATUS_CART,
                                    ).first()
        
        if cart and (timezone.now() - cart.creation_time).days > 7:
            cart.delete()
            cart = None
            
        if not cart:
            cart = Order.objects.create(user=user,
                                        status=Order.STATUS_CART,
                                        amount=0,)
        return cart
    def get_amount(self):
        amount = Decimal(0)
        for item in self.orderitem_set.all():
            amount += item.amount
        return amount
    
    def make_order(self):
        items = self.orderitem_set.all()
        if items and self.status == Order.STATUS_CART:
            self.status = Order.STATUS_WAITING_FOR_PAYMENT
            self.save() 
            auto_payment_unpaid_orders(self.user)

    @staticmethod 
    def get_amount_of_unpaid_orders(user: User):
        amount = Order.objects.filter(user=user,
                                      status=Order.STATUS_WAITING_FOR_PAYMENT,
                                      ).aggregate(Sum('amount'))['amount__sum']
        return  amount or Decimal(0)
        

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.order} --- {self.price} --- {self.product}'

    @property
    def amount(self):
        return self.quantity * (self.price - self.discount)
    

    
    
@transaction.atomic()   
def auto_payment_unpaid_orders(user: User):
    unpaid_orders = Order.objects.filter(user=user, status=Order.STATUS_WAITING_FOR_PAYMENT)

    for order in unpaid_orders:
        if Payment.get_balance(user) < order.amount:
            break
        order.payment = Payment.objects.all().last()
        order.status = Order.STATUS_PAID
        order.save()
        Payment.objects.create(user=user, amount=-order.amount)

@receiver(post_save, sender=OrderItem)
def  recalculate_order_amount_after_save(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()

@receiver(post_save, sender=OrderItem)
def  recalculate_order_amount_after_delete(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()

@receiver(post_save, sender=Payment)
def  auto_payment(sender, instance, **kwargs):
    user = instance.user
    auto_payment_unpaid_orders(user) 
    

shop/forms.py
from django import forms

from shop.models import OrderItem

class AddQuantityForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['quantity']


    

shop/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, DeleteView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from shop.forms import AddQuantityForm
from shop.models import Order, Сategory, Product, OrderItem
from django.utils.decorators import method_decorator



class ProductsListView(ListView):
    model = Product
    template_name = 'shop/shop.html'
    

class ProductsDetailView(DetailView):
    model = Product
    template_name = 'shop/card.html'
    



def get_value(request, value):
    return render(request, 'shop/shop.html')   

def category_filter(request, category_id):
    category = Сategory.objects.get(id=category_id)
    object_list = category.product_set.all()
    name_category = category.name
    print(name_category)
    return render(request, 'shop/shop.html', {'object_list': object_list, 'name_category': name_category})


@login_required(login_url=reverse_lazy('login'))
def add_item_to_cart(request, pk):
    if request.method == 'POST':
        quantity_form = AddQuantityForm(request.POST)
        if quantity_form.is_valid():
            quantity = quantity_form.cleaned_data['quantity']
            if quantity:
                cart = Order.get_cart(request.user)
                # product = Product.objects.get(pk=pk)
                product = get_object_or_404(Product, pk=pk)
                cart.orderitem_set.create(product=product,
                                          quantity=quantity,
                                          price=product.price)
                cart.save()
                return redirect('cart_view')
        else:
            pass
    return redirect('shop')


@login_required(login_url=reverse_lazy('login'))
def cart_view(request):
    cart = Order.get_cart(request.user)
    items = cart.orderitem_set.all()
    context = {
        'cart': cart,
        'items': items,
    }
    return render(request, 'shop/basket.html', context)

@method_decorator(login_required, name='dispatch')
class CartDeleteItem(DeleteView):
    model = OrderItem
    template_name = 'shop/cart.html'
    success_url = reverse_lazy('cart_view')

    # Проверка доступа
    def get_queryset(self):
        qs = super().get_queryset()
        qs.filter(order__user=self.request.user)
        return qs

templates/shop/card.html
{% extends 'base-page.html' %}	
{% load static %}


{% block title %}Товар{% endblock title %}

{% block css%}
<link rel="stylesheet" type="text/css" href="{% static 'style/jquery-ui.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'style/catalog.css'%}">
{% endblock css %}


{% block container %}

	<main>
		<style type="text/css">
			:root{
				--color: #EEF2F8;
				--color_hover: #A8B3D4;
				--bacg_gradient: radial-gradient(72.79% 168.92% at 12.53% 79.42%, #8493BE 0%, #A8B3D4 100%);
				--hover_button: #8192C3;
				--hover_button_active: #7181AE;
			}
		</style>
	
		<section class="section__preview">
			<div class="box-content">
				<div class="breadcrumbs">
					<a href="#">Головна</a> 
					<svg width="11" height="2" viewBox="0 0 11 2" fill="none" xmlns="http://www.w3.org/2000/svg">
						<path d="M0 1H11" stroke="#979AA5" stroke-width="0.5"/>
					</svg>
					<a href="{% url 'shop' %}">Каталог</a> 
					<svg width="11" height="2" viewBox="0 0 11 2" fill="none" xmlns="http://www.w3.org/2000/svg">
						<path d="M0 1H11" stroke="#979AA5" stroke-width="0.5"/>
					</svg>
					{% comment %} <a href="{% url 'category_filter' product.category.id %}">Молдинги для панелей</a>  {% endcomment %}
	 				<span>{{ product.name }}</span>
				</div>
				<div class="section__preview-box">
					<div class="section__preview-images">
						<div class="section__preview-img">
							<div class="section__preview-img_item">
								<img src="{{product.image_url}}">
							</div>
						</div>
					</div>
					<div class="section__preview-info">
						<h1>{{ product.name }}</h1>
						<style>
							.harakt h2{
								color: white;
								margin: 0 0 8px 0;
							}
							.harakt {
								color: white;
								line-height: 1.5;
								margin: 0 0 10px 0;
							}
						</style>
						<div class="harakt">
							<h2>Характеристика:<h2>
							{{ product.note|safe }}
						</div>
						
						<div class="price">{{ product.price }}₴</div>
						<div class="link">
							<form  method="post" action="{% url 'add_item_to_cart' product.pk %}">
								{% csrf_token %}
								{% comment %} <input type="number" name="quantity" value="1" min="1" required id="id_quantity"/> {% endcomment %}
								<button name="quantity" class="buy cart__button" type="submit" value="1" id="id_quantity">
										Додати в кошик
									<svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
										<path d="M5.795 6.25H23.125L21.445 14.64C21.2563 15.5902 20.4136 16.2686 19.445 16.25H8.875C7.86448 16.2586 7.00634 15.512 6.875 14.51L5.355 2.99C5.22462 1.9956 4.37791 1.25152 3.375 1.25H1.125M8.125 23.25C9.22957 23.25 10.125 22.3546 10.125 21.25C10.125 20.1454 9.22957 19.25 8.125 19.25C7.02043 19.25 6.125 20.1454 6.125 21.25C6.125 22.3546 7.02043 23.25 8.125 23.25ZM20.125 23.25C21.2296 23.25 22.125 22.3546 22.125 21.25C22.125 20.1454 21.2296 19.25 20.125 19.25C19.0204 19.25 18.125 20.1454 18.125 21.25C18.125 22.3546 19.0204 23.25 20.125 23.25Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
									</svg>
								</button>
							</form>
							{% comment %} <a href="{% url '' %}" class="buy cart__button">
								Додати в кошик
								<svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path d="M5.795 6.25H23.125L21.445 14.64C21.2563 15.5902 20.4136 16.2686 19.445 16.25H8.875C7.86448 16.2586 7.00634 15.512 6.875 14.51L5.355 2.99C5.22462 1.9956 4.37791 1.25152 3.375 1.25H1.125M8.125 23.25C9.22957 23.25 10.125 22.3546 10.125 21.25C10.125 20.1454 9.22957 19.25 8.125 19.25C7.02043 19.25 6.125 20.1454 6.125 21.25C6.125 22.3546 7.02043 23.25 8.125 23.25ZM20.125 23.25C21.2296 23.25 22.125 22.3546 22.125 21.25C22.125 20.1454 21.2296 19.25 20.125 19.25C19.0204 19.25 18.125 20.1454 18.125 21.25C18.125 22.3546 19.0204 23.25 20.125 23.25Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
								</svg>
							</a> {% endcomment %}
							<div class="count">
								<svg width="18" class="min" height="2" viewBox="0 0 18 2" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path d="M1 1L17 1" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
								</svg>
								<input type="text" name="count" id="count" value="1">
								<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path d="M9 1V17M1 9L17 9" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
								</svg>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="section__preview mobile mobile__slider">
			<div class="box-content">
				<div class="section__preview-info">
					<a href="{% url 'shop' %}" class="back">
						<svg width="6" height="10" viewBox="0 0 6 10" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M5 9L1 5L5 1" stroke="white" stroke-linecap="round" stroke-linejoin="round"/>
						</svg>
						Повернутися назад
					</a>
					<h1>{{ product.name }}</h1>
				
					<div class="slider__mobile-card">
						<div class="slider">
							<div class="section__preview-img_item">
								<img src="{{product.image_url}}">
							</div>
						</div>
					</div>					
					<div class="price">{{ product.price }}₴</div>
					<div class="link" style="margin: 0 0 10px 0">
						<div class="count">
							<svg width="18" class="min" height="2" viewBox="0 0 18 2" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M1 1L17 1" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
							</svg>
							<input type="text" name="count" id="count" value="1">
							<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M9 1V17M1 9L17 9" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
							</svg>
						</div>
						<a href="#" class="buy cart__button">
							Додати в кошик
							<svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M5.795 6.25H23.125L21.445 14.64C21.2563 15.5902 20.4136 16.2686 19.445 16.25H8.875C7.86448 16.2586 7.00634 15.512 6.875 14.51L5.355 2.99C5.22462 1.9956 4.37791 1.25152 3.375 1.25H1.125M8.125 23.25C9.22957 23.25 10.125 22.3546 10.125 21.25C10.125 20.1454 9.22957 19.25 8.125 19.25C7.02043 19.25 6.125 20.1454 6.125 21.25C6.125 22.3546 7.02043 23.25 8.125 23.25ZM20.125 23.25C21.2296 23.25 22.125 22.3546 22.125 21.25C22.125 20.1454 21.2296 19.25 20.125 19.25C19.0204 19.25 18.125 20.1454 18.125 21.25C18.125 22.3546 19.0204 23.25 20.125 23.25Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
							</svg>
						</a>
					</div>
					<div class="harakt">
						<h2>Характеристика:<h2>
						{{ product.note|safe }}
					</div>					
				</div>
			</div>
		</section>
		
		<section class="section__slider">
			<div class="box-content">
				<div class="title-block">
					<h2>Проекти</h2>
				</div>
				<div class="slider__block">
					<div class="slider__block-list">
						<div class="slider__block-item">
							<img src="{% static 'img/Визуализация интерьера 1.png' %}">
						</div>
						<div class="slider__block-item">
							<img src="{% static 'img/Визуализация интерьера 2.png' %}">
						</div>
						<div class="slider__block-item">
							<img src="{% static 'img/Визуализация интерьера 3.png' %}">
						</div>
						<div class="slider__block-item">
							<img src="{% static 'img/Визуализацasdsdия интерьера 3.png' %}">
						</div>
						<div class="slider__block-item">
							<img src="{% static 'img/Визуализация интерьера 1.png' %}">
						</div>
					</div>
					<div class="slider__block-control">
						<div class="sprite-prev">
	                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M16.667 10H3.33366" stroke="#3B3D41" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
								<path d="M8.33301 5L3.33301 10L8.33301 15" stroke="#3B3D41" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
							</svg>
	                    </div>
	                    <div class="controls-dots"></div>
	                    <div class="sprite-next">
	                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M3.33301 10H16.6663" stroke="#3B3D41" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
								<path d="M11.667 5L16.667 10L11.667 15" stroke="#3B3D41" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
							</svg>
	                    </div>
					</div>
				</div>
			</div>
		</section>
		
	</main>

{% endblock container%}

templates/shop/shop.html
{% extends 'base-page.html' %}	
{% load static %}


{% block title %}Каталог{% endblock title %}
{% block css%}
<link rel="stylesheet" type="text/css" href="{% static 'style/jquery-ui.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'style/catalog.css'%}">
{% endblock css %}



{% block container %}

	<main>
		<style type="text/css">
			:root{
				--color: #EEF2F8;
				--color_hover: #F8F8F8;
				--bacg_gradient: radial-gradient(72.79% 168.92% at 12.53% 79.42%, #95AA97 0%, #ABBCAD 100%);
			}
			.section__menu ul li:hover a, .section__menu ul li.active a{
				background: #8B9BCB;
			}
		</style>

		<section class="section__title-page box-content">
			<div class="breadcrumbs">
				<a href="{% url 'index' %}">Головна</a> 
				<svg width="11" height="2" viewBox="0 0 11 2" fill="none" xmlns="http://www.w3.org/2000/svg">
					<path d="M0 1H11" stroke="#979AA5" stroke-width="0.5"/>
				</svg>
				<a href="{% url 'shop' %}">Товари</a> 
				<svg width="11" height="2" viewBox="0 0 11 2" fill="none" xmlns="http://www.w3.org/2000/svg">
					<path d="M0 1H11" stroke="#979AA5" stroke-width="0.5"/>
				</svg>
				<a href="#">{{name_category}}</a> 
			
		</section>
		<p>{{value}}</p>
		<section class="catalog">
			<div class="box-content">
				<div class="catalog__list">

					{% for product in object_list %}
					<div class="catalog__list-item">
						{% csrf_token %}
						<a href="{% url 'shop_detail' product.pk %}" class="images">
							<img src="{{product.image_url}}">
						</a>
						<div class="info">
							<a class="title" href="#">{{ product.name}}</a>
							<span class="attr">{{ product.description }}</span>
							<div class="buy">
								<span class="price">{{ product.price }} ₴</span>
								<form method="post" action="{% url 'add_item_to_cart' product.pk %}">
									{% csrf_token %}
									{% comment %} <input type="number" name="quantity" value="1" min="1" required id="id_quantity"/> {% endcomment %}
									<button name="quantity" class="button__buy" type="submit" value="1" id="id_quantity" >
										
										<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
											<path fill-rule="evenodd" clip-rule="evenodd" d="M6 24.5C6 22.567 7.567 21 9.5 21C11.433 21 13 22.567 13 24.5C13 26.433 11.433 28 9.5 28C7.567 28 6 26.433 6 24.5ZM9.5 23.3333C8.85567 23.3333 8.33333 23.8557 8.33333 24.5C8.33333 25.1443 8.85567 25.6667 9.5 25.6667C10.1443 25.6667 10.6667 25.1443 10.6667 24.5C10.6667 23.8557 10.1443 23.3333 9.5 23.3333Z" fill="#3B3D41"/>
											<path fill-rule="evenodd" clip-rule="evenodd" d="M20 24.5C20 22.567 21.567 21 23.5 21C25.433 21 27 22.567 27 24.5C27 26.433 25.433 28 23.5 28C21.567 28 20 26.433 20 24.5ZM23.5 23.3333C22.8557 23.3333 22.3333 23.8557 22.3333 24.5C22.3333 25.1443 22.8557 25.6667 23.5 25.6667C24.1443 25.6667 24.6667 25.1443 24.6667 24.5C24.6667 23.8557 24.1443 23.3333 23.5 23.3333Z" fill="#3B3D41"/>
											<path fill-rule="evenodd" clip-rule="evenodd" d="M0 1.17644C0 0.526712 0.522334 0 1.16667 0H3.79343C5.54837 0.00268082 7.02999 1.31548 7.25837 3.07003C7.25839 3.07019 7.25835 3.06987 7.25837 3.07003L7.62634 5.88222H26.8333C27.1829 5.88222 27.514 6.04029 27.7356 6.31292C27.9572 6.58555 28.0459 6.94401 27.9773 7.28965L26.0176 17.1582C26.0175 17.1588 26.0174 17.1593 26.0173 17.1598C26.0173 17.1599 26.0173 17.1598 26.0173 17.1598C25.6871 18.8317 24.2192 20.0263 22.5299 19.9996H10.2127C8.44705 20.0119 6.94839 18.6958 6.71836 16.93M6.71836 16.93L4.94502 3.37735C4.869 2.79266 4.37534 2.35414 3.79062 2.35289H1.16667C0.522334 2.35289 0 1.82618 0 1.17644M7.93421 8.23511L9.03164 16.6222C9.10825 17.2116 9.60897 17.6518 10.1984 17.6467L10.2083 17.6466L22.54 17.6467L22.5623 17.6469C23.1274 17.6578 23.6189 17.2588 23.729 16.6999L23.7294 16.6981L25.4099 8.23511H7.93421Z" fill="#3B3D41"/>
										</svg>
									</button>
								</form>
							</div>
						</div>
					</div>
                	{% endfor %}
				</div>
			</div>
			<div class="pagination__catalog">
				<div class="box-content">
					<a href="#">
						<svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M7 13L1 7L7 1" stroke="#3B3D41" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
						</svg>
					</a>
					<ul>
						<li><a style="color: black" href="#"class="active">1</a></li>
					</ul>
					<a href="#">
						<svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M1 13L7 7L1 1" stroke="#3B3D41" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
						</svg>
					</a>
				</div>				
			</div>
			<div class="pagination__catalog mobile">
				<div class="box-content">
					<a href="#">
						<svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M7 13L1 7L7 1" stroke="#3B3D41" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
						</svg>
					</a>
					<ul>
						<li><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#" class="active">4</a></li>
						<li><a href="#" class="dots">...</a></li>
						<li><a href="#">26</a></li>
					</ul>
					<a href="#">
						<svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M1 13L7 7L1 1" stroke="#3B3D41" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
						</svg>
					</a>
				</div>				
			</div>
		</section>
		<section class="catalog__discription">
		</section>
	</main>
	
{% endblock container%}	